Changelog.md
docs/Changelog.md
docs/Supported_Sites.md

Fixing titles

---

Changelog.md
docs/Changelog.md
docs/Supported_Sites.md

Revert "Fixing titles"

---

Supported_Sites.md

Revert "Fix title"

---

comic_dl/comic_dl.py

added quality value parse

---

comic_dl/sites/acQQ.py
comic_dl/sites/comicNaver.py
comic_dl/sites/foolSlide.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/rawSenManga.py
comic_dl/sites/readcomicOnlineto.py
comic_dl/sites/stripUtopia.py

Hi, this is my first contribution ever so please be kind to me.
I added the option to download a comic from a given starting point to the series end, as someone requested in the Issues tab. 
If you want to use this feature you simply need to type a non decimal input, simply speaking any character.
Example:       comic-dl -i "some comic" -rn 4-a

Added series end as range option

---

.gitignore
ReadMe.md
comic_dl/comic_dl.py
comic_dl/config.json.example
comic_dl/configGenerator.py
comic_dl/globalFunctions.py

added the functionality for issue #99 
supported functions are:
* config creation
* series addition
* series removal
* common config vars edit
@Xonshiz feel free to remove my push rights ;)

#99 config generator for autodownload

---

comic_dl/comic_dl.py

#103 if .lock exists resume, else gen lock and start downloading. easy peasy

#103 look for .lock to resume download

---

comic_dl/comic_dl.py
comic_dl/configGenerator.py
comic_dl/globalFunctions.py
comic_dl/sites/acQQ.py
comic_dl/sites/batoto.py
comic_dl/sites/comicNaver.py
comic_dl/sites/comicextra.py
comic_dl/sites/foolSlide.py
comic_dl/sites/hqbr.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/mangaReader.py
comic_dl/sites/rawSenManga.py
comic_dl/sites/readComicBooksOnline.py
comic_dl/sites/readComicsIO.py
comic_dl/sites/readComicsWebsite.py
comic_dl/sites/readcomicOnlineto.py
comic_dl/sites/stripUtopia.py

fix #133 actually nothing was needed to be done to use the next in the correct way. Just change the initial 0 with a 1. The rest was OK as next chapter is equal array length.
Also done the use of the config directly instead of in a tmp

Number friendness for next chapter

---

comic_dl/globalFunctions.py
comic_dl/manga_eden/mangaChapterDownload.py
comic_dl/manga_eden/mangaSearch.py

fix for #129 and #136
and use prepend_zeroes with manga eden

fix for #129 and #136

---

Dockerfile
ReadMe.md

Hi,
I updated the Dockerfile to have a leaner image and updated the documentation (README).

leaner Dockerfile + Docker documentation in Readme.

---

Dockerfile

Fixes #156
- Adding nodejs to docker image.

Add missing Node.js runtime in docker image

---

Contributors.md
comic_dl/globalFunctions.py
comic_dl/honcho.py
comic_dl/manga_eden/mangaChapters.py
comic_dl/sites/acQQ.py
comic_dl/sites/batoto.py
comic_dl/sites/comicNaver.py
comic_dl/sites/comicextra.py
comic_dl/sites/foolSlide.py
comic_dl/sites/hqbr.py
comic_dl/sites/mangaEden.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/mangaReader.py
comic_dl/sites/mangaRock.py
comic_dl/sites/rawSenManga.py
comic_dl/sites/readComicBooksOnline.py
comic_dl/sites/readComicsIO.py
comic_dl/sites/readComicsWebsite.py
comic_dl/sites/readcomicOnlineto.py
comic_dl/sites/stripUtopia.py
docs/Contributors.md

make sites work with auto download

---

comic_dl/sites/batoto.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/mangaReader.py
comic_dl/sites/omgBeauPeep.py
comic_dl/sites/rawSenManga.py

I'd had placed the arrays out of the correct scope so only the last image was downloaded. Fixed now.

Fix of mangaFox to work with parallel downloads & added the missing sites to have parallel download

---

comic_dl/sites/comicNaver.py

fix naver comic download

---

comic_dl/globalFunctions.py

sorry, small bug in previous pr #172 
fixes #171

fix Manga Names with invalid characters prevent creation of directory

---

comic_dl/sites/mangaRock.py

Update Mangarock file decrypting function to python3

fix Xonshiz#208

---

comic_dl/comic_dl.py
comic_dl/configGenerator.py
comic_dl/readcomiconline/RCO.py
comic_dl/readcomiconline/dataUpdate.py
comic_dl/sites/acQQ.py
comic_dl/sites/batoto.py
comic_dl/sites/comicNaver.py
comic_dl/sites/comicextra.py
comic_dl/sites/foolSlide.py
comic_dl/sites/hqbr.py
comic_dl/sites/japscan.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/mangaReader.py
comic_dl/sites/mangaRock.py
comic_dl/sites/rawSenManga.py
comic_dl/sites/readComicBooksOnline.py
comic_dl/sites/readComicsIO.py
comic_dl/sites/readComicsWebsite.py
comic_dl/sites/readcomicOnlineto.py
comic_dl/sites/stripUtopia.py

I used my scraped data from readcomiconline.to to add more functionalities for ease-of-use for downloading comics. See my issue request here. #227 
Download the [data](https://drive.google.com/open?id=1eOjwOQx_LHericcowyBRNIJtZZGMKlp6) and paste it to the same directory as `__main__.py` to make it work.
Basic usage:
**To search for comics**
`python __main__.py -comic-search "<SEARCH QUERY>"`
`-comic-search` lists the comic id of the result
**To show information about a comic**
`python __main__.py -comic-info <COMIC_ID>`
**To download a comic using a Comic ID**
`python __main__.py -i <COMIC_ID> --comic-id`
Will prob. update so that you can perform these commands with the name of the comics instead of the ID.

Used my scraped data from readcomiconline.to to add more functionalities.

---

ReadMe.md

#228
I'm sorry I didn't update the ReadMe.md before issuing my PR.

Updated the Read Me for my PR #228

---

comic_dl/globalFunctions.py
comic_dl/manga_eden/mangaChapterDownload.py
comic_dl/manga_eden/mangaChapters.py
comic_dl/manga_eden/mangaSearch.py
comic_dl/readcomiconline/dataUpdate.py
comic_dl/sites/batoto.py
comic_dl/sites/japscan.py
setup.py
setup2.py

Replaced cfscrape with cloudscraper to fix the "Fooling CloudFlare" loop on ReadComicOnline.to

Replace cfscrape

---

comic_dl/globalFunctions.py
comic_dl/sites/mangaRock.py

One possible implementation of a fix for #234

Sluggify conversion filenames

---

comic_dl/globalFunctions.py
comic_dl/sites/mangaRock.py

This resolves issue #197 and some others. 
Decryption was broken on windows due to byte implementation.

Decryption for Mangarock

---

MANIFEST
ReadMe.md
Supported_Sites.md
comic_dl/config.json.example
comic_dl/honcho.py
comic_dl/readcomiconline/dataUpdate.py
comic_dl/sites/readcomicOnlineli.py
docs/Supported_Sites.md
docs/index.html
setup2.py

Quick search and replace for:-
ReadComicOnlineTo ->ReadComicOnlineli
Readcomiconline.to -> Readcomiconline.li

readcomiconline domain switch

---

Supported_Sites.md
comic_dl/honcho.py
comic_dl/sites/mangaFox.py
comic_dl/sites/mangaHere.py
comic_dl/sites/manganelo.py
comic_dl/sites/rawSenManga.py
docs/Supported_Sites.md

add support for manganato, readmanganato

add support for manganato, readmanganato

---

ReadMe.md

ReadMe.md correct docker image name

ReadMe.md correct docker image name

---

Changelog.md
Supported_Sites.md
comic_dl/__version__.py
comic_dl/honcho.py
comic_dl/sites/foolSlide.py
comic_dl/sites/japscan.py
comic_dl/sites/lectortmo.py
comic_dl/sites/webtoons.py

- Closes #236
- Added support for TMOFans/lectortmo.com [Fix for #231 ]
- Removed some unnecessary comments.
- Fixed an extra method parameter in `japscan`.

Fix for #236 & New website support

---

Changelog.md
Supported_Sites.md
comic_dl/honcho.py
comic_dl/sites/quiremanhua.py
docs/source/supported_sites.rst

New website support added

---

.dockerignore
.gitignore
comic_dl/config.json.example

improve ignores

---

comic_dl/sites/manganelo.py

manganato: if download fails, try the mirror server

manganato: if download fails, try the mirror server

---

Changelog.md
Supported_Sites.md
comic_dl/__version__.py
comic_dl/honcho.py
comic_dl/sites/manganelo.py

new host chapmanganato

---

ReadMe.md

fix docker badge

---

comic_dl/sites/manganelo.py

fix chapmanganato chapter download
- example of chapter not working: -i https://chapmanganato.com/manga-wc973711/chapter-166.2

fix chapmanganato chapter download

---

comic_dl/comic_dl.py

Fix auto download behaves strangely with descending order
- Fix #336

Fix auto download behaves strangely with descending order

---

comic_dl/comic_dl.py

Fix cookie missing

---

comic_dl/honcho.py
comic_dl/sites/manganelo.py

add chapmanganato.to
